import {
  Briefcase,
  Brain,
  FileText,
  Sprout,
  Heart,
  Users,
  Zap,
  Activity,
  Trophy,
  Crown,
  HeartHandshake,
  Compass,
} from "lucide-react";

export const ALL_TESTS = [
  {
    id: "riasec",
    href: "/test?test=riasec",
    title: "Short RIASEC Career Interest Inventory",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Career Interest",
    duration: "5-7 mins",
    desc: "Analyze your interests across 6 dimensions (Realistic, Investigative, Artistic, Social, Enterprising, Conventional) to find your ideal career path.",
    icon: Briefcase,
    iconBg: "bg-[#FEE2E2] text-[#EF4444]",
  },
  {
    id: "hgmi",
    href: "/test?test=hgmi",
    title: "Multiple Intelligence Test (English)",
    subtitle: null,
    category: "Intelligence & Cognitive",
    badge: "Intelligence Profile",
    duration: "8-10 mins",
    desc: "Discover your strengths across 8 dimensions of Howard Gardner's intelligence model (Linguistic, Spatial, Musical, Interpersonal & more).",
    icon: Brain,
    iconBg: "bg-[#EDE9FE] text-[#801A45]",
  },
  {
    id: "hgmi_hindi",
    href: "/test?test=hgmi_hindi",
    title: "बहु-बुद्धि परीक्षण",
    subtitle: "(Multiple Intelligence Test - Hindi)",
    category: "Intelligence & Cognitive",
    badge: "बुद्धि प्रोफ़ाइल",
    duration: "8-10 mins",
    desc: "अपनी बुद्धि की विभिन्न 8 आयामों में क्षमताओं को पहचानें (जैसे: भाषाई, तार्किक, अंतरवैयक्तिक) और अपनी ताकत जानें।",
    icon: FileText,
    iconBg: "bg-[#FEF3C7] text-[#D97706]",
  },
  {
    id: "dweck",
    href: "/test?test=dweck",
    title: "Growth vs. Fixed Mindset Scale",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Mindset Archetype",
    duration: "4-5 mins",
    desc: "Explore how you perceive intelligence, adaptability, and learning. Understand how your beliefs shape your long-term success.",
    icon: Sprout,
    iconBg: "bg-[#DCFCE7] text-[#16A34A]",
  },
  {
    id: "rses",
    href: "/test?test=rses",
    title: "Rosenberg Self-Esteem Scale",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Self-Esteem",
    duration: "3-4 mins",
    desc: "Standardized psychological metric to measure self-worth, inner confidence, and positive self-evaluation across diverse environments.",
    icon: Heart,
    iconBg: "bg-[#FCE7F3] text-[#DB2777]",
  },
  {
    id: "aggression",
    href: "/test?test=aggression",
    title: "Emotional Aggression & Reaction Scale",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Emotional Control",
    duration: "4-6 mins",
    desc: "Understand how you handle high-pressure triggers, frustration, and social conflict resolution under stressful circumstances.",
    icon: Users,
    iconBg: "bg-[#E0E7FF] text-[#6366F1]",
  },
  {
    id: "career-guidance",
    href: "/career-guidance-test",
    title: "Comprehensive Career Guidance Assessment",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Special Assessment",
    duration: "10-12 mins",
    desc: "In-depth multi-dimensional career pathway evaluation with tailored course recommendations across engineering, commerce, management, and arts.",
    icon: Zap,
    iconBg: "bg-[#FEF08A] text-[#CA8A04]",
  },
  {
    id: "emotional",
    href: "/test?test=emotional",
    title: "Emotional Intelligence Scale (EQ)",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Emotional Intelligence",
    duration: "6-8 mins",
    desc: "Evaluate self-awareness, emotional regulation, empathy, and interpersonal rapport in professional and personal contexts.",
    icon: Activity,
    iconBg: "bg-[#CCFBF1] text-[#0D9488]",
  },
  {
    id: "belbin",
    href: "/test?test=belbin",
    title: "Belbin Team Role Assessment",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Team Roles",
    duration: "7-9 mins",
    desc: "Identify your natural team dynamics and behavioral contribution across 8 Belbin team roles (Coordinator, Shaper, Plant, Resource Investigator).",
    icon: HeartHandshake,
    iconBg: "bg-[#F3E8FF] text-[#9333EA]",
  },
  {
    id: "mbti",
    href: "/test?test=mbti",
    title: "Myers-Briggs Type Indicator (MBTI)",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "16 Personalities",
    duration: "8-10 mins",
    desc: "Explore your 4-letter cognitive preferences (Extraversion/Introversion, Sensing/Intuition, Thinking/Feeling, Judging/Perceiving).",
    icon: Compass,
    iconBg: "bg-[#DBEAFE] text-[#2563EB]",
  },
  {
    id: "mcclelland",
    href: "/test?test=mcclelland",
    title: "McClelland Motivation Needs Profile",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Motivation Drivers",
    duration: "6-8 mins",
    desc: "Understand your core motivational archetype across the three seminal needs: Achievement, Affiliation, and Power.",
    icon: Crown,
    iconBg: "bg-[#FFEDD5] text-[#EA580C]",
  },
];
