import {
  Briefcase,
  Brain,
  FileText,
  Sprout,
  Heart,
  Users,
  Activity,
  Sun,
  ShieldCheck,
  Rocket,
  Trophy,
  HeartHandshake,
  Users2,
  Compass,
  Crown,
} from "lucide-react";

export const ALL_TESTS = [
  {
    id: "riasec",
    href: "/test?test=riasec",
    title: "Short RIASEC Career Interest Inventory",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Career Interest",
    duration: "5-7 mins",
    desc: "Analyze your interests across 6 Holland dimensions (Realistic, Investigative, Artistic, Social, Enterprising, Conventional) to find your ideal career path.",
    icon: Briefcase,
    iconBg: "bg-[#FEE2E2] text-[#EF4444]",
  },
  {
    id: "hgmi",
    href: "/test?test=hgmi",
    title: "Multiple Intelligence Test (English)",
    subtitle: null,
    category: "Intelligence & Cognitive",
    badge: "Intelligence Profile",
    duration: "8-10 mins",
    desc: "Discover your strengths across 8 dimensions of Howard Gardner's intelligence model (Linguistic, Spatial, Musical, Interpersonal & more).",
    icon: Brain,
    iconBg: "bg-[#EDE9FE] text-[#801A45]",
  },
  {
    id: "hgmi_hindi",
    href: "/test?test=hgmi_hindi",
    title: "बहु-बुद्धि परीक्षण",
    subtitle: "(Multiple Intelligence Test - Hindi)",
    category: "Intelligence & Cognitive",
    badge: "बुद्धि प्रोफ़ाइल",
    duration: "8-10 mins",
    desc: "अपनी बुद्धि की विभिन्न 8 आयामों में क्षमताओं को पहचानें (जैसे: भाषाई, तार्किक, अंतरवैयक्तिक) और अपनी ताकत जानें।",
    icon: FileText,
    iconBg: "bg-[#FEF3C7] text-[#D97706]",
  },
  {
    id: "dweck",
    href: "/test?test=dweck",
    title: "Growth vs. Fixed Mindset Scale",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Mindset Archetype",
    duration: "4-5 mins",
    desc: "Explore how you perceive intelligence, adaptability, and learning. Understand how your beliefs shape your long-term success.",
    icon: Sprout,
    iconBg: "bg-[#DCFCE7] text-[#16A34A]",
  },
  {
    id: "rses",
    href: "/test?test=rses",
    title: "Rosenberg Self-Esteem Scale",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Self-Esteem",
    duration: "3-4 mins",
    desc: "Standardized psychological metric to measure self-worth, inner confidence, and positive self-evaluation across diverse environments.",
    icon: Heart,
    iconBg: "bg-[#FCE7F3] text-[#DB2777]",
  },
  {
    id: "aggression",
    href: "/test?test=aggression",
    title: "Emotional Aggression & Reaction Scale",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Emotional Control",
    duration: "5-7 mins",
    desc: "Understand how you handle high-pressure triggers, frustration, and social conflict resolution under stressful circumstances.",
    icon: Users,
    iconBg: "bg-[#E0E7FF] text-[#6366F1]",
  },
  {
    id: "emotional",
    href: "/test?test=emotional",
    title: "Emotional Intelligence Scale (EQ)",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Emotional Intelligence",
    duration: "5-7 mins",
    desc: "Evaluate self-awareness, emotional regulation, empathy, and interpersonal rapport in professional and personal contexts.",
    icon: Activity,
    iconBg: "bg-[#CCFBF1] text-[#0D9488]",
  },
  {
    id: "wellbeing",
    href: "/test?test=wellbeing",
    title: "General Psychological Well-Being Scale",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Mental Well-Being",
    duration: "6-8 mins",
    desc: "Comprehensive evaluation of life satisfaction, emotional stability, purposeful vitality, and day-to-day psychological resilience.",
    icon: Sun,
    iconBg: "bg-[#FEF9C3] text-[#CA8A04]",
  },
  {
    id: "peerpressure",
    href: "/test?test=peerpressure",
    title: "Peer Pressure Resistance Scale",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Social Autonomy",
    duration: "5-6 mins",
    desc: "Assess your independent decision-making, personal boundary assertiveness, and resistance against group social pressure.",
    icon: ShieldCheck,
    iconBg: "bg-[#F1F5F9] text-[#475569]",
  },
  {
    id: "enterpreneurship",
    href: "/test?test=enterpreneurship",
    title: "Student Entrepreneurial Aptitude Scale",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Entrepreneurship",
    duration: "6-8 mins",
    desc: "Evaluate your innovation readiness, calculated risk tolerance, creative initiative, and persistence in turning ideas into action.",
    icon: Rocket,
    iconBg: "bg-[#FFEDD5] text-[#EA580C]",
  },
  {
    id: "achievement",
    href: "/test?test=achievement",
    title: "Achievement Motivation Scale",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Goal Drive",
    duration: "4-5 mins",
    desc: "Gauge your internal ambition, drive for high performance, standard of excellence, and tenacity under competitive challenges.",
    icon: Trophy,
    iconBg: "bg-[#FEF08A] text-[#B45309]",
  },
  {
    id: "forgiveness",
    href: "/test?test=forgiveness",
    title: "Forgiveness & Emotional Letting-Go Scale",
    subtitle: null,
    category: "Emotional & Social",
    badge: "Emotional Peace",
    duration: "4-5 mins",
    desc: "Measure your capacity to release grievances, overcome resentment, and foster restorative peace and healing.",
    icon: HeartHandshake,
    iconBg: "bg-[#F3E8FF] text-[#7C3AED]",
  },
  {
    id: "belbin",
    href: "/test?test=belbin",
    title: "Belbin Team Role Assessment",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "Team Roles",
    duration: "7-9 mins",
    desc: "Identify your natural team dynamics and behavioral contribution across 8 Belbin team roles (Coordinator, Shaper, Plant, Resource Investigator).",
    icon: Users2,
    iconBg: "bg-[#EDE9FE] text-[#7C3AED]",
  },
  {
    id: "mbti",
    href: "/test?test=mbti",
    title: "Myers-Briggs Type Indicator (MBTI)",
    subtitle: null,
    category: "Personality & Mindset",
    badge: "16 Personalities",
    duration: "8-10 mins",
    desc: "Explore your 4-letter cognitive preferences (Extraversion/Introversion, Sensing/Intuition, Thinking/Feeling, Judging/Perceiving).",
    icon: Compass,
    iconBg: "bg-[#DBEAFE] text-[#2563EB]",
  },
  {
    id: "mcclelland",
    href: "/test?test=mcclelland",
    title: "McClelland Motivation Needs Profile",
    subtitle: null,
    category: "Career & Ambition",
    badge: "Motivation Drivers",
    duration: "6-8 mins",
    desc: "Understand your core motivational archetype across the three seminal needs: Achievement, Affiliation, and Power.",
    icon: Crown,
    iconBg: "bg-[#FEE2E2] text-[#DC2626]",
  },
];
